### ISSUE TITLE
Add REKKR.wad and REKKRSA.wad to database

### ISSUE THREAD

**Issue by Some1NamedNate** [Ch0wW/wadverifier#5]
`REKKR.wad`
CRC32: 75B5761E
CRC64: 3521DD59D1EC5EC2
SHA256: 50EF7DCC2152BEF5DCB35248E590AAB7A4825ACBE877F8E429F4A865D16A5618
SHA1: 52ED68E190C57A687754D60DC774F99E9648907B
BLAKE2sp: C8A9E62DB0554824F0042531C5441F33041654EFD3F23D22EC1BF3E6048DC0B4

`REKKRSA.wad`
CRC32: 0D294CA5
CRC64: 316D31D1638279A7
SHA256: DD3C7FAE37FF9D8547D9D18F2F4F997206F5076748BE52559B143E72D55A18AB
SHA1: 02217C2CBEB0C83FB05F1FC2A31B11F57DFD15C8
BLAKE2sp: AA8B64DE2740A29CDF2072ECA9DC8B6B6E56545202A5383EA3B6D1AC6478248A

**Comment by Ch0wW** [comment]
Can you tell me if this is a final release or a specific version of REKKR?

EDIT: Could you also give me the MD5 values? That is what it's commonly used for checking the files.

**Comment by Ch0wW** [comment]
Added values for REKKR v1.16. 

If you have the previous releases' MD5, please reopen it. In the meantime, I am closing the ticket.

**Comment by Some1NamedNate** [comment]
Here are the MD5 values:

`REKKR.wad`
`d666daa88cca9ff59816ab2d32aeb4c6`

`REKKRSA.wad`
`b6f4bb3a80f096b6045cfaeb57d4cf29`

Also, REKKR is by Matthew "Revae" Little. Tom Jensen did music for it.
